---
title: "COVID-19 Testing Site Planning"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: bootstrap
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Column {data-width=250}
-----------------------------------------------------------------------

<font size="3.5">

This map displays neighborhood-level data in Hamilton County for informing decisions on COVID testing locations.

Using the menu on the left-hand side of the map, you can toggle variables on/off.

Clicking on a neighborhood displays all variables for that neighborhood

</font>

<font size="3">

Variables Include: 

  * Neighborhood Testing Site Coverage (fraction of neighborhood within 10-min walk of existing test site)

  * Testing Variables
      + Positive Tests per 1000 Population
      + Total Tests per 1000 Population
      + Fraction Positive Tests (Positive Tests / Total Tests)
  
  * American Community Survey Sociodemographic Variables from [The Public Health Disparities Geocoding Project](https://www.hsph.harvard.edu/thegeocodingproject/covid-19-resources/)
      + Percent People of Color (not White Non-Hispanic / Total)
      + Racial/Economic ICE (Index of Concentration at the Extremes for white non-Hispanic high income vs. people of color low income)
      + Total Population 
      + % Crowding (>1 person per room)
      
  * Other American Community Survey Sociodeomgraphic Variables
      + Population Over Age 65
      + Population Density (people per km)
      + Fraction Assisted Income
      + Fraction High School Education
      + Median Income
      + Fraction No Health Insurance
      + Fraction Poverty
      + Fraction Vacant Housing
      + [Deprivation Index](https://geomarker.io/dep_index)
      
  * Facilities at risk for outbreak
      + Long Term Care Facilities (from CHD)
      + Nursing Homes (from Cincy Tech)
      + Prisons and Jails (from Cincy Tech)
      + Shelters
      + CMHA Housing
  
  * Existing Testing Locations
      + CHD Health Centers
  
  * Potential Testing Locations
      + Cincinnati Public Schools
      + Rec Centers

</font>

<br>

<br>

<br>

<font size="2">

Map created by CCHMC GRAPPH.

For questions, contact erika.rasnick@cchmc.org

</font>

Column {data-width=750}
-----------------------------------------------------------------------

```{r data}
library(tidyverse)
library(leaflet)
library(sf)
library(tmap)

d_neigh <- aws.s3::s3readRDS('s3://geomarker/covid_testing_locations/covid_neighborhood_data.rds') %>% 
  st_transform(3735) %>% 
  mutate_at(vars(positive_per_tests, percColor, crowding, 
                 fraction_assisted_income, fraction_high_school_edu, fraction_no_health_ins, 
                 fraction_poverty, fraction_vacant_housing), ~round(.*100)) %>% 
    select(-pop_under_18, -pop_over_50, -pop_over_80) %>% 
  mutate_if(is.numeric, ~round(., 2))

ltcf <- aws.s3::s3readRDS('s3://geomarker/covid_testing_locations/ltcf.rds') %>% 
  st_as_sf(coords = c('lon', 'lat'), crs = 4326) %>% 
  st_transform(3735)

nursing_homes <- aws.s3::s3readRDS('s3://geomarker/covid_testing_locations/nursing_homes.rds') %>% 
  filter(!is.na(lat)) %>% 
  st_as_sf(coords = c('lon', 'lat'), crs = 4326) %>% 
  st_transform(3735)

prisons_jails <- aws.s3::s3readRDS('s3://geomarker/covid_testing_locations/prisons_jails.rds') %>% 
  filter(!is.na(lat)) %>% 
  st_as_sf(coords = c('lon', 'lat'), crs = 4326) %>% 
  st_transform(3735)

schools_reccenters <- aws.s3::s3readRDS('s3://geomarker/covid_testing_locations/schools_reccenters.rds') %>% 
  filter(!is.na(lat)) %>% 
  select(-Tier) %>% 
  rename(lon = long) %>% 
  st_as_sf(coords = c('lon', 'lat'), crs = 4326) %>% 
  st_transform(3735)

schools <- schools_reccenters %>% 
  filter(Group == 'CPS')

reccenters <- schools_reccenters %>% 
  filter(Group == 'Rec_Center')

shelters <- aws.s3::s3readRDS('s3://geomarker/covid_testing_locations/shelters.rds') %>% 
  filter(!is.na(lat)) %>% 
  st_as_sf(coords = c('lon', 'lat'), crs = 4326) %>% 
  st_transform(3735)

cmha <- aws.s3::s3readRDS('s3://geomarker/covid_testing_locations/cmha.rds') %>% 
  filter(!is.na(lat)) %>% 
  st_as_sf(coords = c('lon', 'lat'), crs = 4326) %>% 
  st_transform(3735)

health_centers <- aws.s3::s3readRDS('s3://geomarker/covid_testing_locations/health_centers.rds') %>% 
  st_as_sf(coords = c('lon', 'lat'), crs = 4326) %>% 
  st_transform(3735)

health_center_isochrones_10min_walk <- aws.s3::s3readRDS('s3://geomarker/covid_testing_locations/health_center_isochrones_10min_walk.rds')  %>% 
  st_as_sf()
health_center_isochrones_15min_drive <- aws.s3::s3readRDS('s3://geomarker/covid_testing_locations/health_center_isochrones_15min_drive.rds')  %>% 
  st_as_sf()

test_sites_hc <- aws.s3::s3readRDS("s3://geomarker/covid_testing_locations/test_sites_hc.rds") %>% 
  st_as_sf(coords = c('lon', 'lat'), crs = 4326) %>% 
  st_transform(3735)

test_sites_isochrones_10min_walk <- aws.s3::s3readRDS('s3://geomarker/covid_testing_locations/test_sites_isochrones_10min_walk.rds')  %>% 
  st_as_sf()

test_sites_isochrones_15min_drive <- aws.s3::s3readRDS('s3://geomarker/covid_testing_locations/test_sites_isochrones_15min_drive.rds')  %>% 
  st_as_sf()

test_sites_hc[c(1, 2, 13, 14),1] <- c('Mercy Health West Sleep Center', 
                                      'Flu Clinic at Mercy Health Bond Hill',
                                         'The Jewish Hospital Mercy Health Outpatient Clinic',
                                         'Mercy Health Forest Hills Family Medicine')

test_sites_hc <- test_sites_hc[,1:7]


d_neigh <- d_neigh %>%
  mutate(neigh_area = as.numeric(st_area(.)),
         neigh_intersection = map(row_number(), ~st_intersection(d_neigh[.x,], test_sites_isochrones_10min_walk)),
         intersection_area = as.numeric(map(neigh_intersection, st_area)),
         intersection_area = ifelse(is.na(intersection_area), 0, intersection_area),
         frac_coverage = intersection_area/neigh_area) %>%
  select(-neigh_area, -neigh_intersection, -intersection_area)

city_outline <- aws.s3::s3readRDS("s3://geomarker/geometries/cincinnati_city_outline.rds")
```

```{r map, , fig.width = 13.5, fig.height = 10, fig.align='center'}
tmap_mode('view')

legend_labels <-  c('Positive Tests Per 1000 People' = 'positive_per_1000pop', 
                     'Tests Per 1000 People' = 'tests_per_1000pop', 
                     '% Positive Tests' = 'positive_per_tests', 
                    '% People of Color' = 'percColor', 
                     'Racial/Economic ICE' = 'ICEwnhinc', 
                     'Total Population' = 'pop_total', 
                     'Population Over Age 65' = 'pop_over_65', 
                     'Population Density' = 'pop_density', 
                     '% Crowding' = 'crowding', 
                     '% Assisted Income' = 'fraction_assisted_income', 
                     '% High School Education' = 'fraction_high_school_edu', 
                     'Median Income' = 'median_income', 
                     '% No Health Insurance' = 'fraction_no_health_ins', 
                     '% Poverty' = 'fraction_poverty', 
                     '% Vacant Housing' = 'fraction_vacant_housing', 
                    'Deprivation Index' = 'dep_index', 
                    'Fraction Neighborhood Coverage' = 'frac_coverage')

tm <- tm_shape(d_neigh, 
               name = 'Neighborhoods') +
  tm_polygons(col = "grey50", 
              alpha = 0.2) +
  tm_shape(d_neigh, name = names(legend_labels)[17]) +
  tm_polygons(col = names(d_neigh)[19], 
              title = names(legend_labels)[17],
              alpha = 0.5, 
              palette = '-viridis', 
              style = "cont", 
              popup.vars = legend_labels) +
  tm_shape(d_neigh) +
  tm_polygons(col = names(d_neigh)[c(2:5, 7:11, 14:17)], 
              title = names(legend_labels)[c(1:4, 6:10, 13:16)],
              alpha = 0.5, 
              palette = 'viridis', 
              style = "quantile", 
              popup.vars = legend_labels) +
  tm_shape(d_neigh, name = names(legend_labels)[5]) +
  tm_polygons(col = names(d_neigh)[6], 
              title = names(legend_labels)[5],
              alpha = 0.5, 
              palette = '-viridis', 
              style = "quantile",
              midpoint = 0,
              popup.vars = legend_labels) +
  tm_shape(d_neigh, name = names(legend_labels)[11:12]) +
  tm_polygons(col = names(d_neigh)[c(12:13)], 
              title = names(legend_labels)[11:12],
              alpha = 0.5, 
              palette = '-viridis', 
              style = "quantile",
              popup.vars = legend_labels) +
  tm_facets(as.layers = TRUE, 
            free.scales.fill = TRUE) + 
  tm_shape(ltcf, name = 'Long Term Care Facilities') +
  tm_dots(size = 0.2, 
          col = "black",
          alpha = 0.7) +
    tm_shape(nursing_homes, name = 'Nursing Homes') +
  tm_dots(size = 0.2, 
          col = "blue",
          alpha = 0.7) +
  tm_shape(prisons_jails, name = 'Prisons and Jails') +
  tm_dots(size = 0.2, 
          col = "red",
          alpha = 0.7) +
    tm_shape(schools, name = 'Public Schools') +
  tm_dots(size = 0.2,
          col = "orange",
          alpha = 0.7) +
  tm_shape(reccenters, name = 'Rec Centers') +
  tm_dots(size = 0.2, 
          col = "purple",
          alpha = 0.7) +
  tm_shape(shelters, name = 'Shelters') +
  tm_dots(size = 0.2, 
          col = "green",
          alpha = 0.7) +
  tm_shape(cmha, name = 'CMHA Housing') +
  tm_dots(size = 0.2, id = 'address',
          col = "pink",
          alpha = 0.7) +
    tm_shape(health_centers, name = 'CHD Health Centers') +
  tm_dots(size = 0.2, 
          col = "gray",
          alpha = 0.7) +
  tm_shape(test_sites_hc, name = 'Existing Testing Locations') +
  tm_dots(size = 0.2, 
          col = "white",
          alpha = 0.7) +
  tm_shape(test_sites_isochrones_10min_walk, 
           name = '10-min walk buffer to test site') +
  tm_polygons(col = 'white', alpha = 0.7) +
  tm_shape(test_sites_isochrones_15min_drive, 
           name = '15-min drive buffer to test site') +
  tm_polygons(col = 'gray', alpha = 0.7) +
  tm_shape(city_outline, name = 'City of Cincinnati') +
  tm_lines(lwd=3) +
  tm_scale_bar()

tm %>%
  tmap_leaflet() %>% 
  leaflet::hideGroup(names(legend_labels)[1:16]) %>% 
      leaflet::hideGroup('Long Term Care Facilities') %>% 
    leaflet::hideGroup('Nursing Homes') %>% 
      leaflet::hideGroup('Prisons and Jails') %>% 
        leaflet::hideGroup('Public Schools') %>% 
        leaflet::hideGroup('Rec Centers') %>% 
          leaflet::hideGroup('Shelters') %>% 
            leaflet::hideGroup('CMHA Housing') %>% 
              leaflet::hideGroup('15-min drive buffer to test site') %>% 
  addLegend("bottomright", values = dates,
            colors = "black", 
            labels = "Long Term Care Facilities",
            title = "",
            opacity = 1) %>% 
    addLegend("bottomright", values = dates,
            colors = "blue", 
            labels = "Nursing Homes",
            title = "",
            opacity = 1) %>% 
      addLegend("bottomright", values = dates,
            colors = "red", 
            labels = "Prisons and Jails",
            title = "",
            opacity = 1) %>% 
        addLegend("bottomright", values = dates,
            colors = "orange", 
            labels = "Public Schools",
            title = "",
            opacity = 1) %>% 
        addLegend("bottomright", values = dates,
            colors = "purple", 
            labels = "Rec Centers",
            title = "",
            opacity = 1) %>% 
          addLegend("bottomright", values = dates,
            colors = "green", 
            labels = "Shelters",
            title = "",
            opacity = 1) %>% 
  addLegend("bottomright", values = dates,
            colors = "pink", 
            labels = "CMHA Housing",
            title = "",
            opacity = 1) %>% 
     addLegend("bottomright", values = dates,
            colors = "white", 
            labels = "Existing Testing Locations",
            title = "",
            opacity = 1) %>% 
     addLegend("bottomright", values = dates,
            colors = "gray", 
            labels = "CHD Health Centers",
            title = "",
            opacity = 1) %>% 
      leaflet.extras::addFullscreenControl()

```


